language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
before_script:
  - chmod -R a+x cli-linux
script:
  - ./cli-linux/build.sh
  - ./cli-linux/tests.sh
after_success:
  - ./cli-linux/publish.sh
  - ./cli-linux/docker-publish.sh
notifications:
  email:
    on_success: never
    on_failure: always