language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.301
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/linux/build.sh
  - ./scripts/linux/tests.sh
after_success:
  - ./scripts/linux/publish.sh
  - ./scripts/linux/docker-publish.sh
notifications:
  email:
    on_success: never
    on_failure: always