version: "2"

services:
  api:
    build: ../src/Healthy.Api
    links:
      - mongo
      - redis
    ports:
      - '5000:5000'

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis
    ports:
      - '6379:6379'